---
driver:
  name: docker
driver_config:
    socket: tcp://192.168.59.103:2375

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list: recipe[kibana-authentication-proxy]
    attributes:
